#!/usr/bin/env python3
"""Export a reverse-video-prompt iteration case for GitHub.

This script is intentionally opt-in. It never uploads anything unless the user
passes both --upload issue and --yes. Raw media is not copied unless --copy-media
is explicitly set.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path


CHANGE_LEVELS = [
    "prompt-only",
    "candidate skill rule",
    "reference-template update",
    "eval case",
    "tooling",
]
DEFAULT_REPO = "zhengzhentao86/reverse-video-prompt"


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"-+", "-", value).strip("-")
    return value or "iteration-case"


def read_text_arg(text: str | None, file_path: str | None) -> str:
    if text and file_path:
        raise SystemExit("Use either text or file input, not both.")
    if file_path:
        return Path(file_path).read_text(encoding="utf-8")
    return text or ""


def write_learning_card(path: Path, data: dict[str, str]) -> None:
    lines = []
    for key, value in data.items():
        safe = (value or "").replace("\n", "\n  ")
        lines.append(f"{key}: {safe}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_issue_body(args: argparse.Namespace, prompt_used: str) -> str:
    sections = [
        ("Product category", args.product_category),
        ("Target platform/model", args.target_platform),
        ("Reference", args.reference_desc),
        ("Reference link", args.reference_link),
        ("Generated attempt", args.generated_desc),
        ("Generated attempt link", args.generated_link),
        ("Observed failure", args.observed_failure),
        ("Reusable rule", args.reusable_rule),
        ("Change level", args.change_level),
        ("Privacy note", args.privacy_note),
    ]

    body = [
        "## Iteration Case",
        "",
        "> Generated by `scripts/export_iteration_case.py`.",
        "",
    ]
    for label, value in sections:
        if value:
            body.extend([f"### {label}", "", value.strip(), ""])

    if prompt_used:
        body.extend(["### Prompt used", "", "```text", prompt_used.strip(), "```", ""])

    body.extend(
        [
            "### Checklist",
            "",
            "- [ ] This case does not expose private or unauthorized raw media.",
            "- [ ] The proposed rule is reusable beyond one exact video.",
            "- [ ] The fix is observable from video/audio evidence.",
            "- [ ] The change avoids adding incidental clip-specific details to the main skill.",
            "",
        ]
    )
    return "\n".join(body)


def export_case(args: argparse.Namespace) -> Path:
    now = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    case_slug = slugify(args.case_id or args.title)
    case_dir = Path(args.out_dir) / f"{now}-{case_slug}"
    case_dir.mkdir(parents=True, exist_ok=False)

    prompt_used = read_text_arg(args.prompt_text, args.prompt_file)

    issue_body = build_issue_body(args, prompt_used)
    issue_path = case_dir / "issue.md"
    issue_path.write_text(issue_body, encoding="utf-8")

    learning_card = {
        "case_id": case_slug,
        "product_category": args.product_category,
        "target_market": args.target_platform or "",
        "reference_intent": args.reference_desc or "",
        "generated_failure": args.observed_failure,
        "user_feedback": args.user_feedback or "",
        "root_cause": args.root_cause or "",
        "reusable_rule": args.reusable_rule or "",
        "change_level": args.change_level,
        "prompt_fix_summary": args.prompt_fix_summary or "",
        "risk_of_overfit": args.risk_of_overfit,
        "privacy_note": args.privacy_note,
    }
    write_learning_card(case_dir / "learning-card.yml", learning_card)

    manifest = {
        "title": args.title,
        "created_at_utc": now,
        "case_id": case_slug,
        "raw_media_uploaded": False,
        "media": [],
    }

    if args.media:
        media_dir = case_dir / "media"
        if args.copy_media:
            media_dir.mkdir()
        for item in args.media:
            src = Path(item).expanduser()
            entry = {"source": str(src), "copied": False}
            if args.copy_media:
                if not src.exists():
                    raise SystemExit(f"Media path not found: {src}")
                dst = media_dir / src.name
                shutil.copy2(src, dst)
                entry["copied"] = True
                entry["local_copy"] = str(dst)
            manifest["media"].append(entry)

    (case_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return case_dir


def maybe_upload_issue(args: argparse.Namespace, issue_path: Path) -> None:
    if args.upload == "none":
        return
    if args.upload != "issue":
        raise SystemExit(f"Unsupported upload mode: {args.upload}")
    if not args.yes:
        raise SystemExit("Refusing to upload without --yes.")
    cmd = [
        "gh",
        "issue",
        "create",
        "--repo",
        args.repo,
        "--title",
        args.title,
        "--body-file",
        str(issue_path),
        "--label",
        "iteration-case",
    ]
    subprocess.run(cmd, check=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export a reverse-video-prompt iteration case."
    )
    parser.add_argument("--title", required=True)
    parser.add_argument("--case-id")
    parser.add_argument("--product-category", required=True)
    parser.add_argument("--target-platform")
    parser.add_argument("--prompt-text")
    parser.add_argument("--prompt-file")
    parser.add_argument("--reference-desc")
    parser.add_argument("--reference-link")
    parser.add_argument("--generated-desc")
    parser.add_argument("--generated-link")
    parser.add_argument("--observed-failure", required=True)
    parser.add_argument("--user-feedback")
    parser.add_argument("--root-cause")
    parser.add_argument("--reusable-rule")
    parser.add_argument("--prompt-fix-summary")
    parser.add_argument("--change-level", choices=CHANGE_LEVELS, default="prompt-only")
    parser.add_argument("--risk-of-overfit", choices=["low", "medium", "high"], default="medium")
    parser.add_argument(
        "--privacy-note",
        default="No raw media is uploaded by default. Share only authorized links, screenshots, or descriptions.",
    )
    parser.add_argument("--media", action="append", help="Local media path to include in the manifest.")
    parser.add_argument(
        "--copy-media",
        action="store_true",
        help="Copy media into the local export bundle. This still does not upload it.",
    )
    parser.add_argument("--out-dir", default="iteration-cases")
    parser.add_argument(
        "--repo",
        default=DEFAULT_REPO,
        help=f"GitHub repo in owner/name format. Default: {DEFAULT_REPO}",
    )
    parser.add_argument("--upload", choices=["none", "issue"], default="none")
    parser.add_argument("--yes", action="store_true", help="Confirm upload when --upload is used.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    case_dir = export_case(args)
    issue_path = case_dir / "issue.md"
    maybe_upload_issue(args, issue_path)
    print(f"Exported iteration case: {case_dir}")
    print(f"Issue body: {issue_path}")


if __name__ == "__main__":
    main()
